# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.3.7"

gem "bcrypt", "~> 3.1.7"
gem "jbuilder"
gem "puma", ">= 5.0"
gem "rails", "~> 7.1.5", ">= 7.1.5.1"
gem "sqlite3", ">= 1.4"
gem "tzinfo-data", platforms: [:windows, :jruby]

gem "bootsnap", require: false

group :development, :test do
  gem "factory_bot_rails"
  gem "pry"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-shopify", require: false
end
